name: Akshaynath R
description: >
    Personal blog
about: >
    Backend programmer at Oracle. I spend my free time reading  ML research papers, Deep-learning books and learning from youtube lectures. Interested in Quantum mechanics and Quantum computing. Former GSOC participant (2017) and regional finalist in ACM-ICPC (2016).Founded a startup in college and worked as CTO.Always like to talk about startups and technology.

master_repo: true
url: "https://akshaynathr.github.io"
markdown: kramdown
highlighter: rouge

plugins: ['jekyll-paginate', 'jekyll-gist', 'jekyll-feed']

paginate: 4

logo:             logo.png
disqus_shortname: 'akshaynathr'

rtl: false
owner:
  name:           akshaynathr
  avatar:         "https://avatars3.githubusercontent.com/u/6396634?s=40&v=4"
  email:          "akshaynathr@gmail.com"
  # Social networking links used in footer. Update and remove as you like.
  twitter: r_akshaynath
  github: https://github.com/akshaynathr
  linkedin: https://www.linkedin.com/in/akshaynathr
  # For Google Authorship https://plus.google.com/authorship
  google_plus:

# Analytics and webmaster tools stuff goes here
google_analytics:
google_verify:
# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:
